version: '3.1'

services:

  db:
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 7777:3306

  adminer: # creds: root/root
    image: adminer
    restart: always
    ports:
      - 6000:8080
