version: '3.1'

services:

  db:
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 7777:3306

# Use root/example as user/password credentials

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
